#pragma once

#define MAIN_Version "23141d1"
#define KNX_Version "2.2.2+ee3c00e"
#define MODULE_LogicModule_Version "3.8.0+55beacc"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 8
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 56
#define MODULE_Common_Version "1.5.1+193e462"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 5
#define MODULE_Common_Version_Revision 1
#define MODULE_Common_ETS 21
#define MODULE_DFA_Version "0.7.1+d9ccb83"
#define MODULE_DFA_Version_Major 0
#define MODULE_DFA_Version_Minor 7
#define MODULE_DFA_Version_Revision 1
#define MODULE_DFA_ETS 7
#define MODULE_FileTransferModule_Version "0.1.4+3a96b4e"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 4
#define MODULE_FileTransferModule_ETS 1
#define MODULE_BinaryInput_Version "0.2.1+7b628ef"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 2
#define MODULE_BinaryInput_Version_Revision 1
#define MODULE_BinaryInput_ETS 2
#define MODULE_HardwareConfig_Version "1.0.0+98190e8"
#define MODULE_HardwareConfig_Version_Major 1
#define MODULE_HardwareConfig_Version_Minor 0
#define MODULE_HardwareConfig_Version_Revision 0
#define MODULE_HardwareConfig_ETS 16
#define MODULE_Meter_Version "0.5.0+4680ec0"
#define MODULE_Meter_Version_Major 0
#define MODULE_Meter_Version_Minor 5
#define MODULE_Meter_Version_Revision 0
#define MODULE_Meter_ETS 5
