#pragma once

#define MAIN_Version "5cbf34c"
#define KNX_Version "2.3.1+7124a64"
#define MODULE_LogicModule_Version "4.0.1+2bc2557"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 0
#define MODULE_LogicModule_Version_Revision 1
#define MODULE_LogicModule_ETS 64
#define MODULE_Common_Version "1.7.2+86dc82b"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 7
#define MODULE_Common_Version_Revision 2
#define MODULE_Common_ETS 23
#define MODULE_DFA_Version "0.8.2+7cb2e35"
#define MODULE_DFA_Version_Major 0
#define MODULE_DFA_Version_Minor 8
#define MODULE_DFA_Version_Revision 2
#define MODULE_DFA_ETS 8
#define MODULE_FileTransferModule_Version "0.1.5+178f186"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 5
#define MODULE_FileTransferModule_ETS 1
#define MODULE_BinaryInput_Version "0.2.1+7b628ef"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 2
#define MODULE_BinaryInput_Version_Revision 1
#define MODULE_BinaryInput_ETS 2
#define MODULE_HardwareConfig_Version "1.0.0+2af139a"
#define MODULE_HardwareConfig_Version_Major 1
#define MODULE_HardwareConfig_Version_Minor 0
#define MODULE_HardwareConfig_Version_Revision 0
#define MODULE_HardwareConfig_ETS 16
#define MODULE_Meter_Version "0.5.0+4680ec0"
#define MODULE_Meter_Version_Major 0
#define MODULE_Meter_Version_Minor 5
#define MODULE_Meter_Version_Revision 0
#define MODULE_Meter_ETS 5
