#pragma once

#define MAIN_Version "4d0177c"
#define KNX_Version "2.1.2+764900e"
#define MODULE_Common_Version "1.2.0+9f24e6e"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 2
#define MODULE_Common_Version_Revision 0
#define MODULE_Common_ETS 18
#define MODULE_LogicModule_Version "3.5.2+9a1cfe1"
#define MODULE_LogicModule_Version_Major 3
#define MODULE_LogicModule_Version_Minor 5
#define MODULE_LogicModule_Version_Revision 2
#define MODULE_LogicModule_ETS 53
#define MODULE_FileTransferModule_Version "0.1.0+2669301"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 0
#define MODULE_FileTransferModule_ETS 1
#define MODULE_BinaryInput_Version "0.2.0+9fd5ad1"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 2
#define MODULE_BinaryInput_Version_Revision 0
#define MODULE_BinaryInput_ETS 2
#define MODULE_Meter_Version "0.2.0+453c73b"
#define MODULE_Meter_Version_Major 0
#define MODULE_Meter_Version_Minor 2
#define MODULE_Meter_Version_Revision 0
#define MODULE_Meter_ETS 2
#define MODULE_DFA_Version "0.4.0+3553289"
#define MODULE_DFA_Version_Major 0
#define MODULE_DFA_Version_Minor 4
#define MODULE_DFA_Version_Revision 0
#define MODULE_DFA_ETS 4
